CREATE TABLE ARTEMIA.SPONSOR (
    IDSPONSOR        NUMBER NOT NULL,
    NOM              VARCHAR2(20) NOT NULL,
    TYPE_DE_SPONSOR  VARCHAR2(20) NOT NULL,
    MONTANT          NUMBER NOT NULL,
    COMPTE           VARCHAR2(20),
    CONSTRAINT SPONSOR_PK PRIMARY KEY (IDSPONSOR)
)
TABLESPACE SYSTEM;
